### ISSUE TITLE
#!/bin/sh  + source doesn't work in ubuntu

### ISSUE THREAD

**Issue by qenvio** [kundajelab/genomedisco#1]
It seems ubuntu uses "dash" for "sh" which doesn't have "source"

**Comment by oursu** [comment]
I have fixed the source commands to work on ubuntu. If you get the latest version, does that work for you?

**Comment by qenvio** [comment]
I'm sorry, but now this error appears:
```bash
genomedisco/install_scripts/install_genomedisco.sh: line 54: -e: command not found
```

**Comment by ghost** [comment]
This tool appears to work on my Ubuntu system. That error seems to appear when it cannot find R. When running the install script, it looks like you have to use the --pathtor as specified in the readme.

Hope this helps.

**Comment by oursu** [comment]
I have updated the installation procedure. There is no install shell script anymore, just some python commands. Please try it again and let me know if there are any problems.

**Comment by qenvio** [comment]
Good!
I've tried it on a fresh machine, and after a couple of errors because of dependencies (scipy, sklearn, h5py and psutil), installation and example worked fine.

Many thanks!

:)
